# Глобальные настройки интерфейса
[main]
font=JetBrainsMono Nerd Font:size=13
fields=name,generic,comment,exec
terminal=kitty
prompt="❯ "
icon-theme=Papirus
layer=overlay

# Размеры окна меню
width=40
tabs=4
horizontal-pad=20
vertical-pad=20
inner-pad=10

# Настройка рамки и скруглений в стиле Hyprland
image-size-ratio=0.5
line-height=24
lines=10
border-width=2
border-radius=12

# Подключаем цвета, которые генерирует Pywal
# Этот файл автоматически обновляется при смене обоев через wal
# include=~/.cache/wal/colors-fuzzel.ini
; include=~/.cache/wal/colors-kitty.conf
include=~/.config/fuzzel/colors.ini


; include=
; [colors]
; # Цвет фона (светло-черный)
; background=1e1e2eff
; # Цвет текста по умолчанию
; text=cdd6f4ff
; # Цвет строки ввода (промпта)
; prompt=bac2deff
; # Цвет текста при поиске
; input=cdd6f4ff
; # Цвет иконки лупы/символа
; match=f38ba8ff
; # Цвет фона выделенной строки
; selection=585b70ff
; # Цвет текста выделенной строки
; selection-text=cdd6f4ff
; # Цвет совпадения букв в выделенной строке
; selection-match=f38ba8ff
; # Цвет рамки окна (в тон бордеров Hyprland)
; border=89b4faff
